// auto generated by build/layouts.js

    function get() {
      return `<div class="basic-layout">
    <div class="section-a"></div>
    <div class="section-b"></div>
    <div class="section-c"></div>
</div>`;
   }

   module.exports =  get;
  