// auto generated by build/layouts.js

   module.exports = {
      get
   };

   function get() {
      return `<div class="form-layout">
    <div class="section-a"></div>
    <div class="section-b"></div>
    <div class="section-c"></div>
</div>`;
   }