// auto generated by build/layouts.js

module.exports = {
   get: get
};

const layouts = {
   'basic-layout': require('./basic-layout/basic-layout.html.js'),
	'blank': require('./blank/blank.html.js'),
	'form-layout': require('./form-layout/form-layout.html.js')
};

function get(type) {
   if (layouts[type] == null) {
      console.log('layout not found for ', type);
   }

   return layouts[type].get();
}